project_id = "hchtekfbtcbfsfxkjyfi"

[functions.master-admin-auth]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.generate-property-image]
verify_jwt = false

[functions.verify-admin]
verify_jwt = true

