project_id = "hchtekfbtcbfsfxkjyfi"

[functions.admin-data]
verify_jwt = true

[functions.chat-assistant]
verify_jwt = false

[functions.generate-property-image]
verify_jwt = false

[functions.verify-admin]
verify_jwt = true

[functions.log-customer-activity]
verify_jwt = false

[functions.generate-image-stable]
verify_jwt = false

[functions.ai-reasoning-k2]
verify_jwt = false

