-- Enable REPLICA IDENTITY FULL for complete row data during updates
ALTER TABLE chat_messages REPLICA IDENTITY FULL;
ALTER TABLE chat_conversations REPLICA IDENTITY FULL;
ALTER TABLE chat_user_info REPLICA IDENTITY FULL;
ALTER TABLE customer_activity_history REPLICA IDENTITY FULL;
ALTER TABLE contact_messages REPLICA IDENTITY FULL;
ALTER TABLE assistance_requests REPLICA IDENTITY FULL;
ALTER TABLE properties REPLICA IDENTITY FULL;
ALTER TABLE scraping_jobs REPLICA IDENTITY FULL;