-- Insert seed data for properties
INSERT INTO public.properties (
  title, description, location, price, bedrooms, bathrooms, area, land_size,
  property_type, listing_type, status, features, roi_potential, source_platform,
  created_at, updated_at
) VALUES 
('Luxury Villa in Jubilee Hills', 'Stunning 4BHK villa with modern amenities, spacious rooms, and premium finishes in the heart of Jubilee Hills.', 'Jubilee Hills, Hyderabad', 45000000, 4, 4, 3500, 4500, 'residential', 'sale', 'available', ARRAY['parking','garden','swimming pool','gym','security'], 8.5, 'manual', NOW() - INTERVAL '5 days', NOW()),
('3BHK Apartment in Gachibowli', 'Spacious 3BHK apartment in prime Gachibowli location near IT parks.', 'Gachibowli, Hyderabad', 8500000, 3, 2, 1800, NULL, 'residential', 'sale', 'available', ARRAY['parking','elevator','power backup','security'], 12.5, 'manual', NOW() - INTERVAL '3 days', NOW()),
('Commercial Office Space', 'Prime commercial office space in Madhapur IT hub. Ready to move in.', 'Madhapur, Hyderabad', 15000000, NULL, 3, 2500, NULL, 'commercial', 'sale', 'available', ARRAY['parking','elevator','cafeteria','power backup'], 15.0, 'manual', NOW() - INTERVAL '7 days', NOW()),
('Agricultural Land', 'Fertile agricultural land with water availability in Ranga Reddy District.', 'Ranga Reddy, Telangana', 3500000, NULL, NULL, NULL, 25000, 'agricultural', 'sale', 'available', ARRAY['water supply','road access','electricity'], 6.0, 'manual', NOW() - INTERVAL '10 days', NOW()),
('Residential Plot in Kompally', 'HMDA approved residential plot in developing area with clear title.', 'Kompally, Hyderabad', 5500000, NULL, NULL, NULL, 2400, 'undeveloped', 'sale', 'available', ARRAY['electricity','road access','drainage'], 18.0, 'manual', NOW() - INTERVAL '2 days', NOW()),
('2BHK Apartment for Rent', 'Well-maintained 2BHK apartment available for rent in Kondapur.', 'Kondapur, Hyderabad', 25000, 2, 2, 1200, NULL, 'residential', 'rent', 'available', ARRAY['parking','gym','swimming pool'], NULL, 'manual', NOW() - INTERVAL '1 day', NOW()),
('Commercial Warehouse', 'Large warehouse with loading dock suitable for logistics.', 'Patancheru, Hyderabad', 28000000, NULL, 2, 8000, 15000, 'commercial', 'sale', 'available', ARRAY['parking','loading dock','power backup'], 10.5, 'manual', NOW() - INTERVAL '6 days', NOW()),
('Penthouse in Banjara Hills', 'Exclusive 5BHK penthouse with panoramic city views and premium fixtures.', 'Banjara Hills, Hyderabad', 65000000, 5, 5, 4800, NULL, 'residential', 'sale', 'available', ARRAY['parking','terrace garden','home theater','gym','elevator'], 7.5, 'manual', NOW() - INTERVAL '4 days', NOW()),
('Commercial Shop in Ameerpet', 'Prime retail shop space in busy Ameerpet market with high footfall.', 'Ameerpet, Hyderabad', 12000000, NULL, 1, 800, NULL, 'commercial', 'sale', 'available', ARRAY['parking','water supply','power backup'], 14.0, 'manual', NOW() - INTERVAL '8 days', NOW()),
('4BHK Villa in Kokapet', 'Brand new 4BHK villa in gated community with smart home features.', 'Kokapet, Hyderabad', 35000000, 4, 4, 3200, 3800, 'residential', 'sale', 'available', ARRAY['parking','garden','club house','swimming pool','gym'], 9.5, 'manual', NOW() - INTERVAL '1 day', NOW()),
('1BHK Apartment in Miyapur', 'Affordable 1BHK apartment perfect for bachelors or small families.', 'Miyapur, Hyderabad', 3200000, 1, 1, 650, NULL, 'residential', 'sale', 'available', ARRAY['parking','elevator','security'], 11.0, 'manual', NOW() - INTERVAL '2 days', NOW()),
('Office Space for Rent', 'Fully furnished office space in premium Hitec City building.', 'Hitec City, Hyderabad', 180000, NULL, 2, 1500, NULL, 'commercial', 'rent', 'available', ARRAY['parking','elevator','cafeteria','power backup'], NULL, 'manual', NOW() - INTERVAL '3 days', NOW());