
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hchtekfbtcbfsfxkjyfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjaHRla2ZidGNiZnNmeGtqeWZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3OTA3NzMsImV4cCI6MjA1MzM2Njc3M30.mO4rVWSuf9q25dkFTxqa1Gml-Glp0gKcQZUKqCaM714";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Extend the Database type from types.ts to include chat tables
// This is proper module augmentation
declare module './types' {
  export interface Database {
    public: {
      Tables: {
        chat_conversations: {
          Row: {
            id: string;
            user_id: string | null;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            user_id?: string | null;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string | null;
            created_at?: string;
            updated_at?: string;
          };
        };
        chat_messages: {
          Row: {
            id: string;
            conversation_id: string;
            sender_type: string;
            content: string;
            created_at: string;
            admin_name?: string | null;
            message_type: string;
          };
          Insert: {
            id?: string;
            conversation_id: string;
            sender_type: string;
            content: string;
            created_at?: string;
            admin_name?: string | null;
            message_type?: string;
          };
          Update: {
            id?: string;
            conversation_id?: string;
            sender_type?: string;
            content?: string;
            created_at?: string;
            admin_name?: string | null;
            message_type?: string;
          };
        };
        chat_user_info: {
          Row: {
            id: string;
            conversation_id: string;
            name: string | null;
            email: string | null;
            phone: string | null;
            requirements: string | null;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            conversation_id: string;
            name?: string | null;
            email?: string | null;
            phone?: string | null;
            requirements?: string | null;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            conversation_id?: string;
            name?: string | null;
            email?: string | null;
            phone?: string | null;
            requirements?: string | null;
            created_at?: string;
            updated_at?: string;
          };
        };
      } & Record<string, any>;
    } & Record<string, any>;
  }
}
