
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hchtekfbtcbfsfxkjyfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjaHRla2ZidGNiZnNmeGtqeWZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3OTA3NzMsImV4cCI6MjA1MzM2Njc3M30.mO4rVWSuf9q25dkFTxqa1Gml-Glp0gKcQZUKqCaM714";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
